spring.application.name=ClienteRest
spring.mongodb.uri=mongodb://localhost:27017/CtrolPET
spring.mongodb.username=
spring.mongodb.password=
spring.mongodb.database=CtrolPET
spring.mongodb.host=localhost
cloudinary.cloud_name=drsldzlnp
cloudinary.api_key=166195251295246
cloudinary.api_secret=bTEVy73dpCjwu8G0FM1wkvlcP-w