spring.application.name=CtrolPET
spring.mongodb.uri=mongodb://localhost:27017/CtrolPET
spring.mongodb.username=
spring.mongodb.password=
spring.mongodb.database=CtrolPET
spring.mongodb.host=localhost
cloudinary.cloud_name=dtdm6vduu
cloudinary.api_key=456426256214192
cloudinary.api_secret=WcLX0_LWktT90SBbbAc2nV2ggs8