spring.application.name=CtrolPET
spring.mongodb.uri=mongodb://localhost:27017/CtrolPET
spring.mongodb.username=
spring.mongodb.password=
spring.mongodb.database=CtrolPET
spring.mongodb.host=localhost
spring.mvc.hiddenmethod.filter.enabled=true

